In [19]:
import numpy as np
import pandas as pd

In [20]:
date = pd.read_csv(r'D://Data Science//Machine Learning//Data//orders.csv')
time = pd.read_csv(r'D://Data Science//Machine Learning//Data//messages.csv')

In [21]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [22]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [23]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [24]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

## Working with Dates

In [25]:
# Converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [26]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

### 1. Extract year

In [27]:
date['date_year'] = date['date'].dt.year
date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

### 2. Extract Month

In [28]:
date['month'] = date['date'].dt.month
date.head()

        date  product_id  city_id  orders  date_year  month
0 2019-12-10        5628       25       3       2019     12
1 2018-08-15        3646       14     157       2018      8
2 2018-10-23        1859       25       1       2018     10
3 2019-08-17        7292       25       1       2019      8
4 2019-01-06        4344       25       3       2019      1

In [29]:
date['date_month_name'] = date['date'].dt.month_name()
date.head()

        date  product_id  city_id  orders  date_year  month date_month_name
0 2019-12-10        5628       25       3       2019     12        December
1 2018-08-15        3646       14     157       2018      8          August
2 2018-10-23        1859       25       1       2018     10         October
3 2019-08-17        7292       25       1       2019      8          August
4 2019-01-06        4344       25       3       2019      1         January

### 3. Extract Days

In [30]:
date['date_day'] = date['date'].dt.day
date.head()

,date,product_id,city_id,orders,date_year,month,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

### 4. day of week

In [31]:
date['date_dow'] = date['date'].dt.dayofweek
date.head()

,date,product_id,city_id,orders,date_year,month,date_month_name,date_day,date_dow
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

#### day of week-name

In [32]:
date['date_dow_name'] = date['date'].dt.day_name()
date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,month,date_month_name,date_day,date_dow,date_dow_name
0,2019-12-10,2019,12,December,10,1,Tuesday
1,2018-08-15,2018,8,August,15,2,Wednesday
2,2018-10-23,2018,10,October,23,1,Tuesday
3,2019-08-17,2019,8,August,17,5,Saturday
4,2019-01-06,2019,1,January,6,6,Sunday

#### is weekend

In [33]:
date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Saturday', 'Sunday']), 1, 0)
date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,month,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

#### Extract week of the year

In [36]:
date['date_week'] = date['date'].dt.isocalendar().week
# date['date_week'] = date['date'].dt.week
date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,month,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,2019,1,January,6,6,Sunday,1,1

#### Extract quarter

In [37]:
date['quarter'] = date['date'].dt.quarter
date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,month,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1

#### Extract semester

In [38]:
date['semester'] = np.where(date['quarter'].isin([1, 2]), 1, 2)
date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,month,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1,1

#### Extract time elapsed between dates

In [40]:
import datetime

today = datetime.datetime.today()
print(today)

2026-02-02 11:53:12.833023

In [41]:
today - date['date']

0     2246 days 11:53:12.833023
1     2728 days 11:53:12.833023
2     2659 days 11:53:12.833023
3     2361 days 11:53:12.833023
4     2584 days 11:53:12.833023
                 ...
995   2674 days 11:53:12.833023
996   2615 days 11:53:12.833023
997   2463 days 11:53:12.833023
998   2528 days 11:53:12.833023
999   2302 days 11:53:12.833023
Name: date, Length: 1000, dtype: timedelta64[ns]

In [46]:
(today - date['date']).dt.days

0      2246
1      2728
2      2659
3      2361
4      2584
       ...
995    2674
996    2615
997    2463
998    2528
999    2302
Name: date, Length: 1000, dtype: int64

#### Month passed

In [50]:
np.round((today - date['date']) / np.timedelta64(1, 'm'), 0)
# np.round((today - date['date']).dt.days / 30, 0)

0      3234953.0
1      3929033.0
2      3829673.0
3      3400553.0
4      3721673.0
         ...
995    3851273.0
996    3766313.0
997    3547433.0
998    3641033.0
999    3315593.0
Name: date, Length: 1000, dtype: float64

## Working with time

In [51]:
time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [53]:
# converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [54]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [55]:
time['hour'] = time['date'].dt.hour
time['minute'] = time['date'].dt.minute
time['second'] = time['date'].dt.second

time.head()

,date,msg,hour,minute,second
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

#### Extract time part

In [56]:
time['time'] = time['date'].dt.time
time.head()

,date,msg,hour,minute,second,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

#### time difference

In [57]:
today - date['date']

0     2246 days 11:53:12.833023
1     2728 days 11:53:12.833023
2     2659 days 11:53:12.833023
3     2361 days 11:53:12.833023
4     2584 days 11:53:12.833023
                 ...
995   2674 days 11:53:12.833023
996   2615 days 11:53:12.833023
997   2463 days 11:53:12.833023
998   2528 days 11:53:12.833023
999   2302 days 11:53:12.833023
Name: date, Length: 1000, dtype: timedelta64[ns]

In [61]:
# in seconds

(today - date['date'])/np.timedelta64(1, 's')
# (today - time['date']).dt.total_seconds()

0      1.940972e+08
1      2.357420e+08
2      2.297804e+08
3      2.040332e+08
4      2.233004e+08
           ...
995    2.310764e+08
996    2.259788e+08
997    2.128460e+08
998    2.184620e+08
999    1.989356e+08
Name: date, Length: 1000, dtype: float64

In [62]:
# in minutes

(today - date['date'])/np.timedelta64(1, 'm')

0      3.234953e+06
1      3.929033e+06
2      3.829673e+06
3      3.400553e+06
4      3.721673e+06
           ...
995    3.851273e+06
996    3.766313e+06
997    3.547433e+06
998    3.641033e+06
999    3.315593e+06
Name: date, Length: 1000, dtype: float64

In [63]:
# in hours

(today - date['date'])/np.timedelta64(1, 'h')

0      53915.886898
1      65483.886898
2      63827.886898
3      56675.886898
4      62027.886898
           ...
995    64187.886898
996    62771.886898
997    59123.886898
998    60683.886898
999    55259.886898
Name: date, Length: 1000, dtype: float64