In [1]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression

In [2]:
df = np.round(pd.read_csv(r'D:/Data Science/Machine Learning/Data/50_Startups.csv')[['R&D Spend','Administration','Marketing Spend','Profit']]/10000)
np.random.seed(9)
df = df.sample(5)
df

    R&D Spend  Administration  Marketing Spend  Profit
21        8.0            15.0             30.0    11.0
37        4.0             5.0             20.0     9.0
2        15.0            10.0             41.0    19.0
14       12.0            16.0             26.0    13.0
44        2.0            15.0              3.0     7.0

In [3]:
df = df.iloc[:,0:-1]
df

    R&D Spend  Administration  Marketing Spend
21        8.0            15.0             30.0
37        4.0             5.0             20.0
2        15.0            10.0             41.0
14       12.0            16.0             26.0
44        2.0            15.0              3.0

In [5]:
df.iloc[1,0] = np.nan
df.iloc[3,1] = np.nan
df.iloc[-1,-1] = np.nan

C:\Users\shubh\AppData\Local\Temp\ipykernel_15232\766688332.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[1,0] = np.nan
C:\Users\shubh\AppData\Local\Temp\ipykernel_15232\766688332.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[3,1] = np.nan
C:\Users\shubh\AppData\Local\Temp\ipykernel_15232\766688332.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[-1,-1] = np.nan

In [6]:
df.head()

    R&D Spend  Administration  Marketing Spend
21        8.0            15.0             30.0
37        NaN             5.0             20.0
2        15.0            10.0             41.0
14       12.0             NaN             26.0
44        2.0            15.0              NaN

In [7]:
# Step 1 - Impute all missing values with mean of respective col

df0 = pd.DataFrame()

df0['R&D Spend'] = df['R&D Spend'].fillna(df['R&D Spend'].mean())
df0['Administration'] = df['Administration'].fillna(df['Administration'].mean())
df0['Marketing Spend'] = df['Marketing Spend'].fillna(df['Marketing Spend'].mean())

In [8]:
# 0th Iteration
df0

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37       9.25            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.25            26.00
44       2.00           15.00            29.25

In [10]:
# Remove the col1 imputed value
df1 = df0.copy()

df1.iloc[1,0] = np.nan

df1

    R&D Spend  Administration  Marketing Spend
21        8.0           15.00            30.00
37        NaN            5.00            20.00
2        15.0           10.00            41.00
14       12.0           11.25            26.00
44        2.0           15.00            29.25

In [11]:
# Use first 3 rows to build a model and use the last for prediction

X = df1.iloc[[0,2,3,4],1:3]
X

    Administration  Marketing Spend
21           15.00            30.00
2            10.00            41.00
14           11.25            26.00
44           15.00            29.25

In [12]:
y = df1.iloc[[0,2,3,4],0]
y

21     8.0
2     15.0
14    12.0
44     2.0
Name: R&D Spend, dtype: float64

In [13]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[1,1:].values.reshape(1,2))

d:\Data Science\Machine Learning\ml_env\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([23.14158651])

In [14]:
df1.iloc[1,0] = 23.14

In [15]:
df1

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      23.14            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.25            26.00
44       2.00           15.00            29.25

In [17]:
# Remove the col2 imputed value

df1.iloc[3,1] = np.nan

df1

    R&D Spend  Administration  Marketing Spend
21       8.00            15.0            30.00
37      23.14             5.0            20.00
2       15.00            10.0            41.00
14      12.00             NaN            26.00
44       2.00            15.0            29.25

In [18]:
# Use last 3 rows to build a model and use the first for prediction
X = df1.iloc[[0,1,2,4],[0,2]]
X

    R&D Spend  Marketing Spend
21       8.00            30.00
37      23.14            20.00
2       15.00            41.00
44       2.00            29.25

In [19]:
y = df1.iloc[[0,1,2,4],1]
y

21    15.0
37     5.0
2     10.0
44    15.0
Name: Administration, dtype: float64

In [20]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[3,[0,2]].values.reshape(1,2))

d:\Data Science\Machine Learning\ml_env\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([11.06331285])

In [21]:
df1.iloc[3,1] = 11.06

In [22]:
df1

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      23.14            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.06            26.00
44       2.00           15.00            29.25

In [23]:
# Remove the col3 imputed value
df1.iloc[4,-1] = np.nan

df1

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00             30.0
37      23.14            5.00             20.0
2       15.00           10.00             41.0
14      12.00           11.06             26.0
44       2.00           15.00              NaN

In [24]:
# Use last 3 rows to build a model and use the first for prediction
X = df1.iloc[0:4,0:2]
X

    R&D Spend  Administration
21       8.00           15.00
37      23.14            5.00
2       15.00           10.00
14      12.00           11.06

In [25]:
y = df1.iloc[0:4,-1]
y

21    30.0
37    20.0
2     41.0
14    26.0
Name: Marketing Spend, dtype: float64

In [26]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[4,0:2].values.reshape(1,2))

d:\Data Science\Machine Learning\ml_env\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([31.56351448])

In [27]:
df1.iloc[4,-1] = 31.56

In [28]:
# After 1st Iteration
df1

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      23.14            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.06            26.00
44       2.00           15.00            31.56

In [29]:
# Subtract 0th iteration from 1st iteration

df1 - df0

    R&D Spend  Administration  Marketing Spend
21       0.00            0.00             0.00
37      13.89            0.00             0.00
2        0.00            0.00             0.00
14       0.00           -0.19             0.00
44       0.00            0.00             2.31

In [30]:
df2 = df1.copy()

df2.iloc[1,0] = np.nan

df2

    R&D Spend  Administration  Marketing Spend
21        8.0           15.00            30.00
37        NaN            5.00            20.00
2        15.0           10.00            41.00
14       12.0           11.06            26.00
44        2.0           15.00            31.56

In [31]:
X = df2.iloc[[0,2,3,4],1:3]
y = df2.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[1,1:].values.reshape(1,2))

d:\Data Science\Machine Learning\ml_env\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([23.78627207])

In [32]:
df2.iloc[1,0] = 23.78

In [33]:
df2.iloc[3,1] = np.nan
X = df2.iloc[[0,1,2,4],[0,2]]
y = df2.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[3,[0,2]].values.reshape(1,2))

d:\Data Science\Machine Learning\ml_env\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([11.22020174])

In [34]:
df2.iloc[3,1] = 11.22

In [35]:
df2.iloc[4,-1] = np.nan

X = df2.iloc[0:4,0:2]
y = df2.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[4,0:2].values.reshape(1,2))

d:\Data Science\Machine Learning\ml_env\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([38.87979054])

In [36]:
df2.iloc[4,-1] = 31.56

In [37]:
df2

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      23.78            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.22            26.00
44       2.00           15.00            31.56

In [38]:
df2 - df1

    R&D Spend  Administration  Marketing Spend
21       0.00            0.00              0.0
37       0.64            0.00              0.0
2        0.00            0.00              0.0
14       0.00            0.16              0.0
44       0.00            0.00              0.0

In [40]:
df3 = df2.copy()

df3.iloc[1,0] = np.nan

df3

    R&D Spend  Administration  Marketing Spend
21        8.0           15.00            30.00
37        NaN            5.00            20.00
2        15.0           10.00            41.00
14       12.0           11.22            26.00
44        2.0           15.00            31.56

In [41]:
X = df3.iloc[[0,2,3,4],1:3]
y = df3.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[1,1:].values.reshape(1,2))

d:\Data Science\Machine Learning\ml_env\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([24.57698058])

In [42]:
df3.iloc[1,0] = 24.57

In [43]:
df3.iloc[3,1] = np.nan
X = df3.iloc[[0,1,2,4],[0,2]]
y = df3.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[3,[0,2]].values.reshape(1,2))

d:\Data Science\Machine Learning\ml_env\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([11.37282844])

In [44]:
df3.iloc[3,1] = 11.37

In [46]:
df3.iloc[4,-1] = np.nan

X = df3.iloc[0:4,0:2]
y = df3.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[4,0:2].values.reshape(1,2))

d:\Data Science\Machine Learning\ml_env\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([45.53976417])

In [47]:
df3.iloc[4,-1] = 45.53

In [48]:
df2.iloc[3,1] = 11.22

In [49]:
df3

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      24.57            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.37            26.00
44       2.00           15.00            45.53

In [50]:
df3 - df2

    R&D Spend  Administration  Marketing Spend
21       0.00            0.00             0.00
37       0.79            0.00             0.00
2        0.00            0.00             0.00
14       0.00            0.15             0.00
44       0.00            0.00            13.97

#### MICE Imputation Using Loop (Manual Version)

In [71]:
import pandas as pd
import numpy as np

df = np.round(pd.read_csv(r'D:/Data Science/Machine Learning/Data/50_Startups.csv')[['R&D Spend','Administration','Marketing Spend','Profit']]/10000)
df.head()

   R&D Spend  Administration  Marketing Spend  Profit
0       17.0            14.0             47.0    19.0
1       16.0            15.0             44.0    19.0
2       15.0            10.0             41.0    19.0
3       14.0            12.0             38.0    18.0
4       14.0             9.0             37.0    17.0

In [72]:
np.random.seed(42)

df.loc[df.sample(5).index, "R&D Spend"] = np.nan
df.loc[df.sample(5).index, "Marketing Spend"] = np.nan
df.loc[df.sample(3).index, "Administration"] = np.nan

In [73]:
df.isnull().sum()

R&D Spend          5
Administration     3
Marketing Spend    5
Profit             0
dtype: int64

In [74]:
X = df.drop("Profit", axis=1)
y = df["Profit"]

In [75]:
X = pd.get_dummies(X, drop_first=True)

In [76]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=2
)

In [77]:
print("Missing values in X_train:\n")
print(X_train.isnull().sum())

Missing values in X_train:

R&D Spend          3
Administration     3
Marketing Spend    4
dtype: int64

In [78]:
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer

# -------------------------------
# Copy training data
# -------------------------------
X_train_mice = X_train.copy()

print("\n📌 Original Training Data (with missing values):")
display(X_train_mice.head(10))

# -------------------------------
# Step 1: Initial Mean Imputation
# -------------------------------
init_imputer = SimpleImputer(strategy="mean")
X_train_mice[:] = init_imputer.fit_transform(X_train_mice)

print("\n✅ After Initial Mean Imputation:")
display(X_train_mice.head(10))

# -------------------------------
# Columns with missing values
# -------------------------------
missing_cols = X_train.columns[X_train.isnull().any()]
print("\nColumns with missing values:", missing_cols)

# -------------------------------
# Step 2: Iterative MICE Loop
# -------------------------------
n_iterations = 5

for iteration in range(n_iterations):

    print(f"\n==============================")
    print(f"   ITERATION {iteration+1}/{n_iterations}")
    print(f"==============================")

    for col in missing_cols:

        # Find indices where original training data had missing values
        missing_index = X_train[X_train[col].isnull()].index

        if len(missing_index) == 0:
            continue

        # Split dataset
        train_data = X_train_mice.drop(index=missing_index)
        test_data  = X_train_mice.loc[missing_index]

        X_col_train = train_data.drop(columns=[col])
        y_col_train = train_data[col]

        X_col_test = test_data.drop(columns=[col])

        # Train regression model
        model = LinearRegression()
        model.fit(X_col_train, y_col_train)

        # Predict missing values
        predicted_values = model.predict(X_col_test)

        # Fill values back
        X_train_mice.loc[missing_index, col] = predicted_values

    # ✅ Show dataframe after each iteration
    print(f"\n📌 Data After Iteration {iteration+1}:")
    display(X_train_mice.head(10))

print("\n🎉 Final MICE Imputation Completed!")

📌 Original Training Data (with missing values):

    R&D Spend  Administration  Marketing Spend
24        8.0            10.0             14.0
48        0.0             5.0              0.0
17        NaN            15.0             28.0
12        9.0            13.0             25.0
27        7.0            13.0             35.0
33        6.0            10.0             21.0
16        8.0            12.0             26.0
2        15.0            10.0              NaN
25        6.0            14.0             14.0
14       12.0            16.0             26.0

✅ After Initial Mean Imputation:

    R&D Spend  Administration  Marketing Spend
24   8.000000            10.0        14.000000
48   0.000000             5.0         0.000000
17   7.864865            15.0        28.000000
12   9.000000            13.0        25.000000
27   7.000000            13.0        35.000000
33   6.000000            10.0        21.000000
16   8.000000            12.0        26.000000
2   15.000000            10.0        21.333333
25   6.000000            14.0        14.000000
14  12.000000            16.0        26.000000

Columns with missing values: Index(['R&D Spend', 'Administration', 'Marketing Spend'], dtype='object')

==============================
   ITERATION 1/5
==============================

📌 Data After Iteration 1:

    R&D Spend  Administration  Marketing Spend
24   8.000000            10.0        14.000000
48   0.000000             5.0         0.000000
17  10.885128            15.0        28.000000
12   9.000000            13.0        25.000000
27   7.000000            13.0        35.000000
33   6.000000            10.0        21.000000
16   8.000000            12.0        26.000000
2   15.000000            10.0        38.730905
25   6.000000            14.0        14.000000
14  12.000000            16.0        26.000000

==============================
   ITERATION 2/5
==============================

📌 Data After Iteration 2:

    R&D Spend  Administration  Marketing Spend
24   8.000000            10.0        14.000000
48   0.000000             5.0         0.000000
17  10.998169            15.0        28.000000
12   9.000000            13.0        25.000000
27   7.000000            13.0        35.000000
33   6.000000            10.0        21.000000
16   8.000000            12.0        26.000000
2   15.000000            10.0        38.738449
25   6.000000            14.0        14.000000
14  12.000000            16.0        26.000000

==============================
   ITERATION 3/5
==============================

📌 Data After Iteration 3:

    R&D Spend  Administration  Marketing Spend
24   8.000000            10.0        14.000000
48   0.000000             5.0         0.000000
17  11.002929            15.0        28.000000
12   9.000000            13.0        25.000000
27   7.000000            13.0        35.000000
33   6.000000            10.0        21.000000
16   8.000000            12.0        26.000000
2   15.000000            10.0        38.738282
25   6.000000            14.0        14.000000
14  12.000000            16.0        26.000000

==============================
   ITERATION 4/5
==============================

📌 Data After Iteration 4:

    R&D Spend  Administration  Marketing Spend
24   8.000000            10.0        14.000000
48   0.000000             5.0         0.000000
17  11.002963            15.0        28.000000
12   9.000000            13.0        25.000000
27   7.000000            13.0        35.000000
33   6.000000            10.0        21.000000
16   8.000000            12.0        26.000000
2   15.000000            10.0        38.738281
25   6.000000            14.0        14.000000
14  12.000000            16.0        26.000000

==============================
   ITERATION 5/5
==============================

📌 Data After Iteration 5:

    R&D Spend  Administration  Marketing Spend
24   8.000000            10.0        14.000000
48   0.000000             5.0         0.000000
17  11.002963            15.0        28.000000
12   9.000000            13.0        25.000000
27   7.000000            13.0        35.000000
33   6.000000            10.0        21.000000
16   8.000000            12.0        26.000000
2   15.000000            10.0        38.738281
25   6.000000            14.0        14.000000
14  12.000000            16.0        26.000000

🎉 Final MICE Imputation Completed!

In [ ]:
X_test_mice = init_imputer.transform(X_test)

In [69]:
print(pd.DataFrame(X_train_mice).isnull().sum())

R&D Spend          0
Administration     0
Marketing Spend    0
dtype: int64

#### True MICE in Sklearn

In [70]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

mice = IterativeImputer(max_iter=10, random_state=42)

X_train_mice = mice.fit_transform(X_train)
X_test_mice  = mice.transform(X_test)
print(pd.DataFrame(X_train_mice).isnull().sum())

0    0
1    0
2    0
dtype: int64